replicaCount: 2

image:
  repository: pratik6958/myapp
  tag: v.1.0
  pullPolicy: IfNotPresent

service:
  type: NodePort   # Change to ClusterIP if you donâ€™t need external access
  port: 5000
  nodePort: 30050  # Only used if type: NodePort
